declare const DEBUG: boolean;
declare const GAME_WIDTH: number;
declare const GAME_HEIGHT: number;
declare const BRAIN_SIZE: number;
declare const POPULATION: number;
declare const MUTATION_RATE: number;
declare const TARGET: [number, number];
declare const SPAWN: [number, number];
declare const PAUSE: number;
declare const FRESH_GENES_PERCENT: number;
